Curier/Controllers/OrderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CurierLib.ViewModels;
using CurierLib.Repositories;
using CurierLib.Models;
using CurierLib.Services;

namespace Curier.Controllers
{
    public class OrderController : Controller
    {
        private readonly BaseRepository<Product> repositoryProduct;
        private readonly BaseRepository<Customer> repositoryCustomer;
        private readonly BaseRepository<Courier> repositoryCourier;
        private readonly OrderService orderService;

        public OrderController(BaseRepository<Product> repositoryProduct,
            BaseRepository<Customer> repositoryCustomer,
            BaseRepository<Courier> repositoryCourier, 
            OrderService orderService)
        {
            this.repositoryProduct = repositoryProduct;
            this.repositoryCustomer = repositoryCustomer;
            this.repositoryCourier = repositoryCourier;
            this.orderService = orderService;
        }



        // GET: OrderController
        public ActionResult Index()
        {
            var orders = orderService.GetOrdersList();
            return View(orders);

        }



      
        public ActionResult Create()
        {

            ViewData["Products"] = repositoryProduct.GetAllForRead().Select(x => new SelectDataListItem { Id = x.Id, Text = x.NameTovar }).ToList();
            ViewData["Courier"] = repositoryCourier.GetAllForRead().Select(x => new SelectDataListItem { Id = x.Id, Text = x.Name }).ToList();
            ViewData["Customer"] = repositoryCustomer.GetAllForRead().Select(x => new SelectDataListItem { Id = x.Id, Text = x.Name }).ToList();
            return View();
        }

        // POST: OrderController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OrderToProductViewModel collection)
        {
            try
            {
                orderService.Create(collection);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ViewData["Products"] = repositoryProduct.GetAllForRead().Select(x => new SelectDataListItem { Id = x.Id, Text = x.NameTovar }).ToList();
                ViewData["Courier"] = repositoryCourier.GetAllForRead().Select(x => new SelectDataListItem { Id = x.Id, Text = x.Name }).ToList();
                ViewData["Customer"] = repositoryCustomer.GetAllForRead().Select(x => new SelectDataListItem { Id = x.Id, Text = x.Name }).ToList();
                return View();
            }
        }

        // GET: OrderController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: OrderController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: OrderController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: OrderController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Curier/Controllers/ProductController.cs
using CurierLib.Models;
using CurierLib.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Curier.Controllers
{
    public class ProductController : Controller
    {
        private readonly BaseRepository<Product> repository;

        public ProductController(BaseRepository<Product> repository)
        {
            this.repository = repository;
        }

        public ActionResult Index()
        {
            var models = repository.GetAllForRead(); 
            return View(models);
        }

        // GET: TovarController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TovarController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TovarController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product model)
        {
            try
            {
                repository.Add(model);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(model);
            }
        }

        // GET: TovarController/Edit/5
        public ActionResult Edit(int id)
        {
            var model = repository.GetOne(id);
            return View(model);
        }

        // POST: TovarController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product model)
        {
            try
            {
                repository.Update(model);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(model);
            }
        }

        // GET: TovarController/Delete/5
        public ActionResult Delete(int id)
        {
            var model = repository.GetOne(id);
            repository.Remove(model);
            return RedirectToAction(nameof(Index));
        }

        
    }
}

Curier/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Curier</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Curier</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
           
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courier" asp-action="Index">Курьеры</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Заказчики</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Заказы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Товар</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Create">Создать заказ</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Curier - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>